// Mocks generated by Mockito 5.4.6 from annotations
// in prvin/test/features/ai/domain/usecases/ai_analytics_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prvin/features/ai/domain/entities/analytics_data.dart' as _i2;
import 'package:prvin/features/ai/domain/repositories/ai_analytics_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAnalyticsData_0 extends _i1.SmartFake implements _i2.AnalyticsData {
  _FakeAnalyticsData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AIAnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIAnalyticsRepository extends _i1.Mock
    implements _i3.AIAnalyticsRepository {
  MockAIAnalyticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AnalyticsData> generateAnalytics({
    required String? userId,
    required _i2.DateRange? period,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateAnalytics, [], {
              #userId: userId,
              #period: period,
            }),
            returnValue: _i4.Future<_i2.AnalyticsData>.value(
              _FakeAnalyticsData_0(
                this,
                Invocation.method(#generateAnalytics, [], {
                  #userId: userId,
                  #period: period,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AnalyticsData>);

  @override
  _i4.Future<List<String>> getTagSuggestions(String? taskTitle) =>
      (super.noSuchMethod(
            Invocation.method(#getTagSuggestions, [taskTitle]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<_i2.TaskCategory> getCategorySuggestion(String? taskTitle) =>
      (super.noSuchMethod(
            Invocation.method(#getCategorySuggestion, [taskTitle]),
            returnValue: _i4.Future<_i2.TaskCategory>.value(
              _i2.TaskCategory.work,
            ),
          )
          as _i4.Future<_i2.TaskCategory>);

  @override
  _i4.Future<List<_i2.FocusRecommendation>> getFocusRecommendations(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFocusRecommendations, [userId]),
            returnValue: _i4.Future<List<_i2.FocusRecommendation>>.value(
              <_i2.FocusRecommendation>[],
            ),
          )
          as _i4.Future<List<_i2.FocusRecommendation>>);

  @override
  _i4.Future<List<_i2.TaskPattern>> analyzeTaskPatterns(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeTaskPatterns, [userId]),
            returnValue: _i4.Future<List<_i2.TaskPattern>>.value(
              <_i2.TaskPattern>[],
            ),
          )
          as _i4.Future<List<_i2.TaskPattern>>);

  @override
  _i4.Future<List<_i2.ProductivityTrend>> getProductivityTrends({
    required String? userId,
    required _i2.DateRange? period,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductivityTrends, [], {
              #userId: userId,
              #period: period,
            }),
            returnValue: _i4.Future<List<_i2.ProductivityTrend>>.value(
              <_i2.ProductivityTrend>[],
            ),
          )
          as _i4.Future<List<_i2.ProductivityTrend>>);

  @override
  _i4.Future<List<_i2.FocusPattern>> getFocusPatterns({
    required String? userId,
    required _i2.DateRange? period,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFocusPatterns, [], {
              #userId: userId,
              #period: period,
            }),
            returnValue: _i4.Future<List<_i2.FocusPattern>>.value(
              <_i2.FocusPattern>[],
            ),
          )
          as _i4.Future<List<_i2.FocusPattern>>);

  @override
  _i4.Future<void> saveAnalyticsData(_i2.AnalyticsData? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveAnalyticsData, [data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.AnalyticsData>> getHistoricalAnalytics({
    required String? userId,
    required _i2.DateRange? period,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHistoricalAnalytics, [], {
              #userId: userId,
              #period: period,
            }),
            returnValue: _i4.Future<List<_i2.AnalyticsData>>.value(
              <_i2.AnalyticsData>[],
            ),
          )
          as _i4.Future<List<_i2.AnalyticsData>>);

  @override
  _i4.Future<void> clearExpiredAnalytics({Duration? olderThan}) =>
      (super.noSuchMethod(
            Invocation.method(#clearExpiredAnalytics, [], {
              #olderThan: olderThan,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
