// Mocks generated by Mockito 5.4.6 from annotations
// in prvin/test/features/pomodoro/domain/usecases/pomodoro_timer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:prvin/features/pomodoro/domain/entities/pomodoro_session.dart'
    as _i4;
import 'package:prvin/features/pomodoro/domain/repositories/pomodoro_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PomodoroRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPomodoroRepository extends _i1.Mock
    implements _i2.PomodoroRepository {
  MockPomodoroRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PomodoroSession>> getAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSessions, []),
            returnValue: _i3.Future<List<_i4.PomodoroSession>>.value(
              <_i4.PomodoroSession>[],
            ),
          )
          as _i3.Future<List<_i4.PomodoroSession>>);

  @override
  _i3.Future<List<_i4.PomodoroSession>> getSessionsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsForDate, [date]),
            returnValue: _i3.Future<List<_i4.PomodoroSession>>.value(
              <_i4.PomodoroSession>[],
            ),
          )
          as _i3.Future<List<_i4.PomodoroSession>>);

  @override
  _i3.Future<List<_i4.PomodoroSession>> getSessionsByType(
    _i4.SessionType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsByType, [type]),
            returnValue: _i3.Future<List<_i4.PomodoroSession>>.value(
              <_i4.PomodoroSession>[],
            ),
          )
          as _i3.Future<List<_i4.PomodoroSession>>);

  @override
  _i3.Future<List<_i4.PomodoroSession>> getSessionsForTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsForTask, [taskId]),
            returnValue: _i3.Future<List<_i4.PomodoroSession>>.value(
              <_i4.PomodoroSession>[],
            ),
          )
          as _i3.Future<List<_i4.PomodoroSession>>);

  @override
  _i3.Future<_i4.PomodoroSession?> getSessionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionById, [id]),
            returnValue: _i3.Future<_i4.PomodoroSession?>.value(),
          )
          as _i3.Future<_i4.PomodoroSession?>);

  @override
  _i3.Future<_i4.PomodoroSession?> getActiveSession() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSession, []),
            returnValue: _i3.Future<_i4.PomodoroSession?>.value(),
          )
          as _i3.Future<_i4.PomodoroSession?>);

  @override
  _i3.Future<String> createSession(_i4.PomodoroSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createSession, [session]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateSession(_i4.PomodoroSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSession(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllSessions, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
