// Mocks generated by Mockito 5.4.6 from annotations
// in prvin/test/core/widgets/one_click_language_toggle_button_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:prvin/core/bloc/app_bloc.dart' as _i2;
import 'package:prvin/features/task_management/domain/entities/task.dart'
    as _i5;
import 'package:prvin/features/task_management/domain/repositories/task_repository.dart'
    as _i3;
import 'package:prvin/features/task_management/domain/usecases/task_usecases.dart'
    as _i8;
import 'package:prvin/features/task_management/presentation/bloc/task_bloc.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppState_0 extends _i1.SmartFake implements _i2.AppState {
  _FakeAppState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskRepository_1 extends _i1.SmartFake
    implements _i3.TaskRepository {
  _FakeTaskRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskState_2 extends _i1.SmartFake implements _i4.TaskState {
  _FakeTaskState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTask_3 extends _i1.SmartFake implements _i5.Task {
  _FakeTask_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppBloc extends _i1.Mock implements _i2.AppBloc {
  MockAppBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAppState_0(this, Invocation.getter(#state)),
          )
          as _i2.AppState);

  @override
  _i6.Stream<_i2.AppState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.AppState>.empty(),
          )
          as _i6.Stream<_i2.AppState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i2.AppEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i2.AppEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.AppState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i2.AppEvent>(
    _i7.EventHandler<E, _i2.AppState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i7.Transition<_i2.AppEvent, _i2.AppState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i2.AppState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskBloc extends _i1.Mock implements _i4.TaskBloc {
  MockTaskBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTaskRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TaskRepository);

  @override
  _i4.TaskState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTaskState_2(this, Invocation.getter(#state)),
          )
          as _i4.TaskState);

  @override
  _i6.Stream<_i4.TaskState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.TaskState>.empty(),
          )
          as _i6.Stream<_i4.TaskState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void add(_i4.TaskEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i4.TaskEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.TaskState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i4.TaskEvent>(
    _i7.EventHandler<E, _i4.TaskState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i7.Transition<_i4.TaskEvent, _i4.TaskState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i7.Change<_i4.TaskState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskUseCases extends _i1.Mock implements _i8.TaskUseCases {
  MockTaskUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTaskRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.TaskRepository);

  @override
  _i6.Stream<List<_i5.Task>> get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: _i6.Stream<List<_i5.Task>>.empty(),
          )
          as _i6.Stream<List<_i5.Task>>);

  @override
  _i6.Future<_i5.Task> createTask(_i5.TaskCreateRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [request]),
            returnValue: _i6.Future<_i5.Task>.value(
              _FakeTask_3(this, Invocation.method(#createTask, [request])),
            ),
          )
          as _i6.Future<_i5.Task>);

  @override
  _i6.Future<_i5.Task> updateTask(
    String? taskId,
    _i5.TaskUpdateRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [taskId, request]),
            returnValue: _i6.Future<_i5.Task>.value(
              _FakeTask_3(
                this,
                Invocation.method(#updateTask, [taskId, request]),
              ),
            ),
          )
          as _i6.Future<_i5.Task>);

  @override
  _i6.Future<void> deleteTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.Task>> getTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksForDate, [date]),
            returnValue: _i6.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i6.Future<List<_i5.Task>>);

  @override
  _i6.Future<List<_i5.Task>> getTodayTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayTasks, []),
            returnValue: _i6.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i6.Future<List<_i5.Task>>);

  @override
  _i6.Future<List<_i5.Task>> getWeekTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getWeekTasks, []),
            returnValue: _i6.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i6.Future<List<_i5.Task>>);

  @override
  _i6.Future<List<_i5.Task>> getOverdueTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getOverdueTasks, []),
            returnValue: _i6.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i6.Future<List<_i5.Task>>);

  @override
  _i6.Future<_i5.Task> completeTask(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [taskId]),
            returnValue: _i6.Future<_i5.Task>.value(
              _FakeTask_3(this, Invocation.method(#completeTask, [taskId])),
            ),
          )
          as _i6.Future<_i5.Task>);

  @override
  _i6.Future<List<_i5.Task>> searchTasks(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTasks, [query]),
            returnValue: _i6.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i6.Future<List<_i5.Task>>);

  @override
  _i6.Future<List<_i5.Task>> getTasksByTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByTag, [tag]),
            returnValue: _i6.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i6.Future<List<_i5.Task>>);

  @override
  _i6.Future<List<_i5.Task>> getTasksByCategory(_i5.TaskCategory? category) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByCategory, [category]),
            returnValue: _i6.Future<List<_i5.Task>>.value(<_i5.Task>[]),
          )
          as _i6.Future<List<_i5.Task>>);
}
